extends: airbnb-base

parser: "@babel/eslint-parser"

parserOptions:
  requireConfigFile: false

globals:
  __DEBUG_SERVER_ERRORS__: true
  __SERVER_ERRORS__: true
  fabric: true

env:
  browser: false
  node: true
